### ISSUE TITLE
Consider adding strong name signing

### ISSUE THREAD

**Issue by purepvd** [riok/mapperly#1086]
**Is your feature request related to a problem? Please describe.**
Unable to compile code with this project as my company uses strong name signing and all referenced libraries must be strong name signed. The error looks like this:

`CSC: Error CS8002 : Referenced assembly 'Riok.Mapperly.Abstractions, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.`

**Describe the solution you'd like**
Add strong name signing the projects.

**Describe alternatives you've considered**
Tried to use the remove runtime dependencies with `PrivateAssets="All" ExcludeAssets="runtime"` but that didn't work. I may use `StrongNamer` for now but don't like doing this as it makes managing the dependency more difficult.

**Additional context**
None

**Comment by latonz** [comment]
What error do you get when excluding the runtime assets? Have you tried the latest next release (see docs [here](https://mapperly.riok.app/docs/getting-started/installation/)).

Regarding strong naming: we probably won‘t introduce SN since it doesn‘t bring a lot of benefits on newer .NET runtimes but it brings quite some complexity and limitations to Mapperly (e.g. what dependencies).
See also:
https://github.com/MudBlazor/MudBlazor/issues/7696#issuecomment-1782945903 and others.

**Comment by purepvd** [comment]
Thanks @latonz that is helpful. I will instead consider removing the strong naming from our code base (🤞). We use MudBlazor too and it must be signed as there haven't been issues with it.

I didn't mean excluding runtime assets didn't work, but merely that it didn't work as a workaround.
