### ISSUE TITLE
Option to disable EnumUnderlayingType conversions

### ISSUE THREAD

**Issue by klastarnstrom** [riok/mapperly#1176]
**Describe the bug**
When disabling `MappingConversionType.StringToEnum` conversion, string to enum conversion results in generated code where string is parsed to int, resulting in runtime errors. 

My .editorconfig contains this: 

```editorconfig
dotnet_diagnostic.RMG037.severity = error # Unmapped target enum value
dotnet_diagnostic.RMG038.severity = error # Unmapped source enum value
```

**Declaration code**
```csharp
[Mapper(EnabledConversions = MappingConversionType.All & ~MappingConversionType.StringToEnum)]
public partial class MyMapper
{
    public partial ToType Map(FromType from);
}

public class ToType
{
    public MyEnum Value { get; set; }
}

public enum MyEnum
{
    FirstValue
}

public class FromType
{
    public string Value { get; set; }
}
```

**Actual relevant generated code**
```csharp
// <auto-generated />
#nullable enable
namespace Blue.ServiceInterface
{
    public partial class MyMapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "3.4.0.0")]
        public partial global::Blue.ServiceInterface.ToType Map(global::Blue.ServiceInterface.FromType from)
        {
            var target = new global::Blue.ServiceInterface.ToType();
            target.Value = (global::Blue.ServiceInterface.MyEnum)int.Parse(from.Value);
            return target;
        }
    }
}
```

**Expected relevant generated code**
I expect the code to generate an error when building

**Environment (please complete the following information):**
- Mapperly Version: 3.4.0
- .NET Version: NET 8
- Target Framework: net8.0
- Compiler Version: 
- C# Language Version: 12.0
- IDE: JetBrains Rider 2023.3.1
- OS: Windows 11

**Additional context**
Also mentioned this problem in [this Stack Overflow question](https://stackoverflow.com/questions/78154653/how-can-i-get-build-time-errors-on-string-to-enum-mappings)

**Comment by latonz** [comment]
This is expected behaviour. Mapperly tries to build a conversion using all enabled [conversions](https://mapperly.riok.app/docs/configuration/conversions/) in order of their priority. In this case the `StringToEnum` conversion is disabled. If Mapperly cannot map to the enum directly, it tries to map to the underlaying type and cast that value to the enum type. If you don't want this to happen you may need to disable the explicit cast conversion as well.
Just reporting an error for all string to enum mappings is not supported by Mapperly.
