### ISSUE TITLE
Ignore nested Properties

### ISSUE THREAD

**Issue by AceHack** [riok/mapperly#395]
**Is your feature request related to a problem? Please describe.**
I would like to have an array like syntax to avoid nested properties

**Comment by latonz** [comment]
Could you elaborate a bit more on your use case? What exactly do you need this functionality for?

**Comment by TimothyMakkison** [comment]
**The problem**
Mapperly currently supports defining nested mapping properties, however it does not support ignoring nested members. In some cases this can break logic or create unwanted warnings that cannot be suppressed via mapperly.

```C#
// Here we want to ignore sources Id and UnmappedMember, 
// the target Id will be set via a different explicit mapping and UnmappedMember does not have a corresponding member.
public class NestedChild
{
    // Other members...
    public int Id { get; set; }

    public string UnmappedMember { get; set; }
}
public class NestedChildDto
{
    // Other members
    public Guid Id { get; set; }
}

// Example of nested explicit mapping
[MapProperty("Manufacturer.MyID", "Producer.Id"] // Map property with a different name in the target type
public static partial CarDto MapCarToDto(Car car);
```

**Describe the solution you'd like**
`MapperIgnoreTarget` and `MapperIgnoreSource` should be updated to support a `params string` similar to `[MapProperty]`. `MappingBodyBuilders` should be updated to support nested Ignore. This will likely use some recursion where each step knows its current member handle so it knows which nested ignores it corresponds to. 

**Notes**
I suspect this hasn't been done because it could break the resuing of similar mapping methods. If two mappings share a member type but one ingores a property, the other mapping may reuse this mapping resulting in s subtle bug. When a mapping delegate is created it should record what configurations were used to create it. When checking if a mapper already exists this can be used to ensure that a compatible mapper is reused. `[MapProperty]` appears to avoid this by creating the object and then updating properties via accessible setters.
I haven't confirmed if this would be a problem. It would require a lot of work to fix 😄 

```C#
// Here MapToTailDto is created where Bushiness is not mapped over
[MapperIgnoreTarget("Tail.Bushiness")]
public static partial CatDto Map(Cat car);

// MapToTailDto is reused and Bushiness will not be mapped
public static partial DogDto Map(Dog car);
```

**Comment by AceHack** [comment]
I'll go ahead and close this. I got everything working. Thanks for this wonderful project.  I'm using an asp.net core web api with EF, Mediatr, and this project.  Makes for a very slick experience.

**Comment by TimothyMakkison** [comment]
> I'll go ahead and close this. I got everything working.

What was your work around? I thought you made this issue after reading #392 

> Thanks for this wonderful project. I'm using an asp.net core web api with EF, EF Migrations, Mediatr, and this project. Makes for a very slick experience. Code first, all the way.

Have you tried [Mediator](https://github.com/martinothamar/Mediator) it's a source generated version of Mediatr.
