### ISSUE TITLE
`@` in variable names is ignored

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [riok/mapperly#402]
**Describe the bug**
If a map is declared with a parameter name being a keyword escaped with `@` (e.g., `Dto Map(MyObject @object)`), the generator fails because `@` gets ignored.

**To Reproduce**
```C#
[Mapper]
public partial class Mapper
{
    public partial string DomainToDto(object @object);
}
```
Which gives this code-gen
```C#
#nullable enable
public partial class Mapper
{
    public partial string DomainToDto(object object) // Notice: this is invalid C# and causes the error
    {
        return object.ToString();
    }
}
```

**Expected behavior**
The generated code is syntactically sound.

**Environment (please complete the following information):**
- Mapperly Version: 2.8.0
- .NET Version:  .NET 6.0.408
- Target Framework: .net6.0
- IDE: Rider 2022.3.3
- OS: Windows 11

**Comment by TimothyMakkison** [comment]
Thanks for the bug report.

This is also happens when reserved keywords are used for properties, fields, object factories or user defined mappings. Using `CreateValidIdentifier` in the constructor for `MethodParameter` will solve this issue for partial mappers. 
I don't know how to prevent this issue for other members, perhaps updating `SyntaxFactoryHelper` will work.

```C#
public static string CreateValidIdentifier(string identifier)
{
    return SyntaxFacts.GetKeywordKind(identifier) != SyntaxKind.None ? $"@{identifier}" : identifier;
}

// adding to MethodParameter solves this issue
public MethodParameter(int ordinal, string name, ITypeSymbol type)
{
    Ordinal = ordinal;
    Name = SyntaxFactoryHelper.CreateValidIdentifier(name);
    Type = type;
}
```

**Comment by latonz** [comment]
I think the simplest would be to add new methods `Identifier` and `IdentifierName` in the `Riok.Mapperly.Emit.SyntaxFactoryHelper` which handle this and replace all calls to `Microsoft.CodeAnalysis.CSharp.SyntaxFactory.Identifier` and `Microsoft.CodeAnalysis.CSharp.SyntaxFactory.IdentifierName` with calls to `Riok.Mapperly.Emit.SyntaxFactoryHelper.Identifier` and `Riok.Mapperly.Emit.SyntaxFactoryHelper.IdentifierName`.

**Comment by Ilia-Kosenkov** [comment]
I am unfamiliar with mapperly code base, but I built a couple of small source generators at my dayjob. Aren't there ways to ask Roslyn to provide exact identifier names with `@` prefixes if applicable?

**Comment by latonz** [comment]
I couldn‘t find a Roslyn API for this. Do you know one?

**Comment by Ilia-Kosenkov** [comment]
Let me see if I can find something.

**Comment by Ilia-Kosenkov** [comment]
Ok, found one. I started from here https://github.com/riok/mapperly/blob/5d32b569d0f844b250f2b97bf15815a0f9184ba8/src/Riok.Mapperly/Symbols/MethodParameter.cs#L16-L17
Modified one of the tests to generate source with `@object` parameter name instead of `source` and debugged around. Long story short, you rely on `.Name`, and I learned the hard way it is not always the best thing. Instead, I prefer to call `.ToDisplayString()`, which may be slower, but gives you more fine-grained control. In this particular case, we might be interested in 

```c#
    symbol.ToDisplayString(
            new SymbolDisplayFormat(
                parameterOptions: SymbolDisplayParameterOptions.IncludeName,
                miscellaneousOptions: SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers
            )
        );
```
[`SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.symboldisplaymiscellaneousoptions?view=roslyn-dotnet-4.3.0#fields)

Sorry I do not have a truly reproducible example to showcase this, but I got a lame screenshot from the debug session of my IDE 
![image](https://user-images.githubusercontent.com/8782986/236767545-6a768eeb-779c-458e-9555-bb018c0f86d8.png)
 As you can see, `test` contains exactly `"@object"`.

**Comment by latonz** [comment]
Relevant roslyn implementation:
https://github.com/dotnet/roslyn/blob/604c14b472a6df581a0a02fe5f33fa131d6c6954/src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.cs#L60-L98

This is only available on symbols... Therefore Mapperly has two options:
* Instead of accessing `.Name` on symbols where escaping is required,  use a new extension method `EscapedName()` which uses the `ToDisplayString` with a display format which only extracts the escaped name.
* Replicate the roslyn escape logic in the syntax factory helper (see [previous commit](https://github.com/riok/mapperly/issues/402#issuecomment-1537502407))

I think I'd prefer the second approach as names could still be stored as strings everywhere, no matter whether they need to be escaped and since escaping is not needed everywhere (eg. not when using the name in a file name).
