### ISSUE TITLE
Mapping string[] to string[] throws CS8081

### ISSUE THREAD

**Issue by Sjoerdsjoerd** [riok/mapperly#413]
**Describe the bug**
Mapping string array to a string array throws a CS8081: "Expression does not have a name".

The picture describes the error:
![afbeelding](https://user-images.githubusercontent.com/19996084/236788515-5191574f-1f95-4ca0-9c82-59b1cf5faab8.png)

**To Reproduce**
1. Use the code snippets and check the generated code

**Expected behavior**
No CS8081 exception in the generated code.
Also the generated code is different with no generated code header comment which is strange behavior?

**Code snippets**
A.cs:
``` cs
namespace Namespace;

using System;

public class A
{
	public string[] Items { get; set; }

	public A()
	{
		Items = Array.Empty<string>();
	}

	public A(string[] array)
	{
		Items = array;
	}
}
```
B.cs:
``` cs
// //------------------------------------------------------------------------------
// // <auto-generated>
// //     This code was generated by a tool.
// //
// //     Changes to this file may cause incorrect behavior and will be lost if
// //     the code is regenerated.
// // </auto-generated>
// //------------------------------------------------------------------------------
namespace AnotherNamespace
{
	using System;

	public class A
	{
		public string[] Items { get; set; }

		public A()
		{
			Items = Array.Empty<string>();
		}

		public A(string[] array)
		{
			Items = array;
		}
	}
}
```
Mapper.cs:
``` cs
namespace Namespace;

using Riok.Mapperly.Abstractions;

[Mapper]
public partial class Mapper
{
	public partial A AtoA(AnotherNamespace.A abcde);
}
```

**Environment:**
- Mapperly Version: 2.8.0
- .NET Version: .NET SDK 7.0.203
- Target Framework: net6.0
- IDE: Visual Studio v17.5.5
- OS: Windows 11 22H2

**Comment by TimothyMakkison** [comment]
Thanks for the bug report. 

I think you're experiencing an issue similar to #229 where mapperly doesn't correctly handle nullable array elements.
I'm guessing you have nullable enabled in your main project with nullable disabled for `AnotherNamespace.A` because it's auto generated code.

If it's possible you could try enabling nullable for your auto generated code, in the meantime I'll look at #229 again.

**Comment by latonz** [comment]
I think beside the nullable problem, the main problem here is the `nameof(source[i])` part, as an indexer is not valid inside a nameof expression.

@Sjoerdsjoerd I cannot reproduce the issue with the code you provided with v2.8.0/main and neither with enabled/disabled nullable reference types. Do you have `UseDeepCloning`, `ThrowOnMappingNullMismatch`, or `ThrowOnPropertyMappingNullMismatch` enabled? Do both properties have an accessible getter/setter? What nullable reference types settings do the classes `Namespace.A` and `AnotherNamespace.A` have?

**Comment by TimothyMakkison** [comment]
I don't know if someone else is going to create a PR but I was thinking of creating `SyntaxFactoryHelper.ConstantNameOf` to use for throw expressions (and maybe the enum matching arms not 100% sure). `ConstantNameOf` would use whatever trick Roslyn uses for [CA1507](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1507).

**Comment by latonz** [comment]
@TimothyMakkison feel free to open a PR, but I think it would make sense to discuss the proposed solution here first. I think in this case, we cannot throw an `ArgumentNullException` since it isn't really an argument but an element of the argument. IMO `NullReferenceException` would be more appropriate in for loops with indexed sources. If this is adjusted, probably the nameof problem isn't relevant anymore anyway.
