### ISSUE TITLE
Allow user to specify user mapping method

### ISSUE THREAD

**Issue by lucasteles** [riok/mapperly#598]
Sometimes we need to map the same types in different ways without having to add mutability to the target class to use `After/Before` mapping

A solution would be a way to specify how the property should be mapped

```csharp
public class Foo
{
    public required int A { get; init; }
    public required int B { get; init; }
}

public class FooDto
{
    public required TimeSpan A { get; init; }
    public required TimeSpan B { get; init; }
}

[Mapper]
public partial class FooMapper
{
    public int MapHours(TimeSpan a) => a.Hours * 100;
    public int MapSeconds(TimeSpan b) => b.Seconds * 10;

    [MapProperty(nameof(FooDto.A), method: nameof(MapHours))]
    [MapProperty(nameof(FooDto.B), method: nameof(MapSeconds))]
    public partial Foo Map(FooDto dto);
}

```

**Comment by latonz** [comment]
This was already discussed in https://github.com/riok/mapperly/discussions/162 and won't be implemented in Mapperly.

You could use `[MapProperty("A.Hours", "Hours")]` to map the hours of the timespan directly (https://github.com/riok/mapperly/issues/453 could also be helpful).
However, this probably won't work for you, because you multiply it with 100 / 10. I'm not sure if this multiplication should belong to a mapper... If you really want to do that, you can always do it in [after map](https://mapperly.riok.app/docs/configuration/before-after-map).
