### ISSUE TITLE
Use interface with a static abstract member on class managed by Mapperly

### ISSUE THREAD

**Issue by trejjam** [riok/mapperly#673]
**Is your feature request related to a problem? Please describe.**
Use interface with a static abstract member on class managed by Mapperly

**Describe the solution you'd like**
I would like that this code will generate mapping:
```cs
public interface IMyInterface
{
  static abstract void Update(SourceDto source, DestinationDto destination);
}

[Mapper]
public partial class MyMapping : IMyInterface
{
  public static partial void Update(SourceDto source, DestinationDto destination);
}
```

**Describe alternatives you've considered**
A form of a hack is this solution:
```cs
public interface IMyInterface
{
  static abstract void Update(SourceDto source, DestinationDto destination);
}

public class MyMapping : IMyInterface
{
  public static void Update(SourceDto source, DestinationDto destination) => MyMappingInternal.Update(source, destination);
}

[Mapper]
public static partial class MyMappingInternal
{
  public static partial void Update(SourceDto source, DestinationDto destination);
}
```

**Additional context**
For some reason class with the attribute `[Mapper]` does not generate static members when the class itself is not static. The issue with static interface members is that interface cannot be defined on class which is static at the same time it's members are static

**Comment by TimothyMakkison** [comment]
> For some reason class with the attribute [Mapper] does not generate static members when the class itself is not static.

**Comment by cremor** [comment]
Can't that be solved by checking the candidate method itself so that only static methods are used when generating code for a static method?

**Comment by TimothyMakkison** [comment]
> Can't that be solved by checking the candidate method itself so that only static methods are used when generating code for a static method?

Yeah that would work 👍 It might cause some  confusion when misused tho. @latonz WDYT?

**Comment by trejjam** [comment]
Can be a solution to have a different lookup for static and instance methods?

One is allowed to use the other but not the other way around?

**Comment by TimothyMakkison** [comment]
> I think instance mapping methods should be allowed to use static methods, but not the other way around. Just like the normal C# method usage rules are.

Mapperly will use static methods in an instance method mapper.

```C#
[Mapper]
public partial class Mapper
{
    public partial B MapTo(A src);

    public static string Mapped(int src) => throw new NotImplementedException();
}

public record A(int Value);

public record B(string Value);

// generates
public partial global::B MapTo(global::A src)
{
    var target = new global::B(Mapped(src.Value)); // mapped is used here.
    return target;
}
```

While it is possible to support generating static mapper methods in a class instance, I suspect that it was never added due to a combination of difficulty, no use case (up until now) and potential confusion. 

In the following a user may mistakingly think that `MapStatic` would use `IntoString`.
```C#
[Mapper]
public partial class Mapper
{
    public partial B MapInstance(A src); // will use IntoString

    public static partial B MapStatic(A src); // would not use IntoString

    public string IntoString(int src) => throw new NotImplementedException();
}
```

**Comment by trejjam** [comment]
In the end, I choose a more simple solution. If I may ask you for a review it would be nice

**Comment by latonz** [comment]
Rel. https://github.com/riok/mapperly/pull/681#issuecomment-1697329056

I understand your use case. Up until now, there was no use case for this. Due to the missing use case, the complexity this would add to Mapperly and the possible emerging confusion for a user by this feature, this is not supported by Mapperly.

From a Mapperly internal perspective, every time Mapperly references anything (another user-defined, user-implemented or generated mapping, an external mapping or an object factory), it would need to check whether it can call the target based on whether it is static or not and whether the call takes place in a static context or not. The current resolution for mappings simply works on the types involved, this wouldn't work anymore.

But the second, in my opinion almost bigger point, is the possible confusion of the user. The switch from instance to static contexts may not always be comprehensible.
Given these:
```c#
record A1(B1 Value);
record A2(B2 Value);
record B1(C1 Value);
record B2(C2 Value);
record C1(int Value);
record C2(int Value);
```

```c#
[Mapper]
partial class Mapper
{
    public partial A2 Map(A1 source);
    public static partial A2 MapStatic(A1 source);
}
```

This would generate two separate mappings and generated static methods to map from `B1` to `B2` (`MapToB`) and from `C1` to `C2` (`MapToC`). `MapToB` would be called from `Map` and `MapStatic`. `MapToC` would be called from `MapToB`.

But if the mapper now contains another customised mapping for the C mapping or even a user implemented mapping:
```c#
[Mapper]
partial class Mapper
{
    public partial A2 Map(A1 source);
    public static partial A2 MapStatic(A1 source);
    private C2 ManualMapToC(C1 source) => new(source.Value * 10);
}
```
What happens now? `ManualMapToC` cannot be called from `MapStatic`/`MapToB`. The user may expect `ManualMapToC` to be called from the `Map` call tree. The solution would probably be to generate the `MapToB` twice, once for the static context and once for the instance context. With bigger object trees this leads to even more complexity and possible confusion on the user side. This could also lead to a lot of duplicated code.

I'm not a fan of an additional configuration, I don't see the benefit of it. What exactly does it enable?
I think if we want to support this use case in Mapperly we have the following options (let me know if you can think of additional options 😊):
* Do not support this use-case at all (status quo)
* If there is one static partial method in the Mapper, do not allow any instance members in the mapper class (treat it as static class, diagnostic with a severity of error)
* Try to support mixed static/non-static resolution and source generation as outlined above. This would need a more in-depth concept on how to address the mentioned points above and how to technically implement this in Mapperly.

**Comment by trejjam** [comment]
> What exactly does it enable?

My use case is to do some heavy lifting which is done in a generic manner with the need of a mapper.
Let's say I have a method like this:
```cs
async Task SynchronizeAsync<TSource, TDestination, TMapper>(
  IDataSource dataSource,
  IDataDestination dataDestination
) where TMapper : IMapper<TSource, TDestination>
{
    var source = await dataSource.LoadDataAsync<TSource>();

    var destination = TMapper.MapToDestination(source);

    await dataDestination.ProcessDataAsync<TDestination>(destination );
}

// first invocation
await SynchronizeAsync<Source1Dto, Target1Dto, MyMapper1>(
  dataSource,
  dataDestination
);

// another invocation
await SynchronizeAsync<Source2Dto, Target2Dto, MyMapper2>(
  dataSource,
  dataDestination
);

interface IMapper<TSource, TDestination>
{
    static abstract TDestination MapToDestination(TSource source);
}
```

Of course, I can create an instance and pass it, but I technically do not need to. It also does not allocate additional memory.

> I'm not a fan of an additional configuration, I don't see the benefit of it. What exactly does it enable?

The configuration is a way how library users can opt in for static members.

I also find it difficult to manage static and non-static method calls, after the first line of chaining it becomes madness. That's why I introduced the configuration. Its purpose is to pretend that everything should be static and it should block any non-static methods by diagnostic, or compilation (since you opt-in for static and then you write your own mapping which will not be static, the compiler will tell you clearly about your mistake. You/we do not need to write custom diagnostics). The compiler also covers the possibility that you write:
```
[Mapper(GenerateStaticMethods = true)]
public partial class CarMapper : IMyInterface
{
    public partial CarDto ToDto(Car car);
}
```
The compiler will tell you that `partial ToDto` must be both static or non-static.

___

The mixed mode is interesting, but it requires a lot of changes. To track if a syntax tree is static or not. And so on. It's an interesting topic but I am not sure if it's worthy

**Comment by trejjam** [comment]
I see non-static class with static methods as a kind of exception to the current behavior. That's why I add `GenerateStaticMethods`. If the functionality is automatic it can be triggered by accident and create confusion (in my opinion). Maybe it can be resolved with a descriptive diagnostic message.

**Comment by latonz** [comment]
Ah got it, your proposal is the second option I described, just with an additional configuration flag. I don't see much benefit in the additional configuration flag. If a user creates a mapper with static and instance members, diagnostics would be reported. If these diagnostics are descriptive the user should know what's the problem. So I don't think we need the opt in behaviour. To conclude the implementation would look like this: If any user defined mapping is static, set the entire mapper as static (like the class itself would be static). Scan all members of the class and report an error on all instance members.

I'd drop de mixed mode (option 3) for now due to the very high complexity / possible user confusion.

**Comment by trejjam** [comment]
Yes, I may be clearer in the beginning. Thank you for guidance, I will implement it in a free time

**Comment by latonz** [comment]
A small hint: It is probably enough to adjust the constructor parameter `descriptor.Symbol.IsStatic` of `SourceEmitterContext`  in `Riok.Mapperly.Emit.SourceEmitter.Build` for the source code generation to work correctly (despite the extraction of whether we should assume a static mapper and emitting the diagnostics for mixed mappers).
